// Generated by Assets/Hananoki/SceneViewTools/Editor/Localize/ja-JP.csv
namespace Hananoki.SceneViewTools {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _TimeScaleSlider => L.Tr( "TimeScaleSlider" );
		public static string _Executeevenwithmultiplesceneviews => L.Tr( "Execute even with multiple scene views" );
		public static string _Syncscenecameratogamecamera => L.Tr( "Sync scene camera to game camera" );
		public static string _MatchGameView => L.Tr( "Match GameView" );
		public static string _ToggleOrthographic => L.Tr( "Toggle Orthographic" );
	}
}
