// Generated by Assets/Hananoki/SceneViewTools/Localize/en-US.csv

namespace HananokiEditor.SceneViewTools {
	public static class L {
		public static string Tr( int n ) {
			try {
				return EditorLocalize.GetPakage( Package.name ).m_Strings[ n ];
			}
			catch( System.Exception ) {
			}
			return string.Empty;
		}
	}
	public static class S {
		public static string _TimeScaleSlider => L.Tr( 0 );
		public static string _Executeevenwithmultiplesceneviews => L.Tr( 1 );
		public static string _Syncscenecameratogamecamera => L.Tr( 2 );
		public static string _MatchGameView => L.Tr( 3 );
		public static string _ToggleOrthographic => L.Tr( 4 );
	}

#if UNITY_EDITOR
  public class LocalizeEvent {
    [HananokiEditorLocalizeRegister]
    public static void Changed() {
			EditorLocalize.Load( Package.name, "bee5713c1b219a941859080a666e8150" );
		}
	}
#endif
}
